language: ruby

before_install:
  # Travis bundler versions are quite out of date and can cause install errors
  # see: https://github.com/rubygems/rubygems/issues/1419
  - gem update bundler

rvm:
  - 2.0.0
  - 2.1
  - 2.4
